# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.yml'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  netVersion: '6.0.x'
  releaseSuffix: ''

name: 4.0.$(date:yyMM).$(date:dd)$(rev:r)
steps:
- task: NuGetToolInstaller@1
  displayName: Install Latest Nuget

- task: Bash@3
  displayName: Install MAUI
  inputs:
    targetType: 'inline'
    script: 
      dotnet workload install android ios maccatalyst tvos macos maui wasm-tools

- task: NuGetCommand@2
  displayName: Nuget Restore
  inputs:
    restoreSolution: '$(solution)'
  
- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Version=$(Build.BuildNumber)$(releaseSuffix) /p:AssemblyVersion=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: CopyFiles@2
  displayName: Copy Files to $(build.artifactstagingdirectory)
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/Dsoft.*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts drop
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
