<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<SignAssembly>False</SignAssembly>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DSoft.System.Mvvm" Version="3.5.2604.111" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DSoft.Messaging\DSoft.MessageBus.csproj" />
	</ItemGroup>

</Project>
